name: "Firebase App Distribution Github Action"
author: "Burhan Khanzada"
description: "Github action that uploads single or multiple apps to firebase app distribution"

inputs:
  service_account_key_json:
    description: "Google cloud platform project service account key"
    required: true

  app_id:
    description: "Firebase App id"
    required: false

  app:
    description: "App to upload (.apk or .ipa)"
    required: false

  groups:
    description: "Groups of testers seperated by comma"
    required: false

  multiple_apps_json:
    description: "Json file for multiple apps"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "package"
  color: "yellow"
